DROP DATABASE IF EXISTS Uploads;
CREATE database Uploads;
USE Uploads;
CREATE TABLE galleries (
    id INT AUTO_INCREMENT PRIMARY KEY,
	gallery_code VARCHAR(25) NOT NULL,
    auth_code VARCHAR(25) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE images (
    id INT AUTO_INCREMENT PRIMARY KEY,
	filename VARCHAR(15) NOT NULL,
    auth_code VARCHAR(25) NOT NULL,
    path VARCHAR(100) NOT NULL,
    url VARCHAR(100) NOT NULL,
    filesize INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE links (
    id INT AUTO_INCREMENT PRIMARY KEY,
    gallery_code VARCHAR(25) NOT NULL,
    filename VARCHAR(15) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);